[all:vars]
ansible_user=root
ansible_python_interpreter=/run/current-system/sw/bin/puthon3
ansible_ssh_private_key_file=id_rsa
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
[routers]
rtr ansible_host=192.168.10.1

[servers]
srv ansible_host=192.168.10.20

[clients]
clipc ansible_host=192.168.20.30
